### PR TITLE
📦 Game Update 13.05.2022 (1.38.2.9 (1458))

### PR DESCRIPTION
**Pull request by slauko**

### CODE REVIEW

**Comment by slauko** [comment]
oops there was another update this night, will open another with newest

**Comment by slauko** [comment]
should be gucci now

**Comment by afeer123** [comment]
nice

**Comment by afeer123** [comment]
Game Update 16.05.2022

**Comment by Pesimist44** [comment]
New update came the game please update offsets

**Comment by slauko** [comment]
pushed update to my fork

**Comment by afeer123** [comment]
[Game Update 24.05.2022 (1.38.3.2 (1462))]updated 24.05.2022 offset the offset he did not work

**Comment by afeer123** [comment]
> [游戏更新 24.05.2022 （1.38.3.2 （1462））]更新 24.05.2022 抵消了他不起作用的偏移
How should I do

**Comment by afeer123** [comment]
game is update hi

**Comment by afeer123** [comment]
thank you very much

**Pull request closed without merging**
