### PR TITLE
🔧 Updated dwForceAttack2 signature

### PR DESCRIPTION
**Pull request by TosoxDev**
Why did the pull request (#31) got declined? He was right the signature is outdated and this is the correct fix.
Grabbed and tested the extra offset by myself.

### CODE REVIEW

**Comment by fener123321** [comment]
new update

**Comment by NotUserName1337** [comment]
update it pls

**Comment by dinoajero** [comment]
is there an update in config.json?

**Comment by since1910** [comment]
güncelleme çalısmıyor

**Pull request merged**
