### PR TITLE
Update config.json

### PR DESCRIPTION
**Pull request by tuziluojie**
hazedump

### CODE REVIEW

**Comment by Westwood15487** [comment]
The new update doesn't work

**Comment by Westwood15487** [comment]
Is there a way to make it working

**Comment by Pesimist44** [comment]
A new update came to the game

**Comment by NotUserName1337** [comment]
Update pls

**Comment by ReactiioN1337** [comment]
I can see no reason why `m_iDefaultFOV` should be removed. However, I've added `m_iFOV` as requested.

**Comment by ReactiioN1337** [comment]
@Westwood15487 @Pesimist44 @NotUserName1337 a regular update has nothing to do with this issue/pull-request. For updates, see [here](https://github.com/frk1/hazedumper#informations).

**Pull request closed without merging**
