### PR TITLE
📦 Game Update 28.05.2020 (49.8 MB)

### PR DESCRIPTION
**Pull request by s0t7x**
Einfach der neuste dump^^
Hoffe es hilft^^

### CODE REVIEW

**Comment by keshav089** [comment]
ESP and Bhop working
Aimbot and Trigger Not working CSGO 
can u share ur Settings.txt  i want o verify

**Comment by s0t7x** [comment]
> ESP and Bhop working
> Aimbot and Trigger Not working CSGO
> can u share ur Settings.txt i want o verify

I don't know what your imagination of "Settings.txt" may be but if you want to take a look at the Hazedumper configuration, go ahead, it's there and i did not change anything in it.

When it comes to reading offsets, i fetch the latest json from this repository, parse it and assign offsets i need to variables. If you want to get an idea you may look at this [Gist](https://gist.github.com/s0t7x/e03ddf27c521fe3c4366c0a917ff784c).

So to clarify: I am pretty sure latest hazedumper Offsets (unfortunately not on this repo right now, therefore the pull-request) are correct!

Regardless your comment really has nothing to do with this pull-request. If you have questions regarding game-hacking or your code, get into some known fora like unknowncheats and ask there!

**Comment by imbarismustafa** [comment]
@s0t7x Thank you for the update mate! Everything works flawlessly. Well in this case I mean the offsets are correct because after I updated the offsets, Bhop, Chams, Glow, NoFlash, Radar and Trigger functionalities started working!

**Comment by ReactiioN1337** [comment]
Unfortunately, I don't receive any notifications here. As soon as I'm home and there was an update, I update the repo. I don't see it before that.

**Pull request closed without merging**
