### PR TITLE
dwLocalPlayer new value 0xD36B94

### PR DESCRIPTION
**Pull request by imbarismustafa**
dwLocalPlayer new value 0xD36B94

### CODE REVIEW

**Comment by keshav089** [comment]
> dwLocalPlayer new value 0xD36B94

Aimbot/triggerbot not working i since 15 days only esp works

**Comment by s0t7x** [comment]
> > dwLocalPlayer new value 0xD36B94
> 
> Aimbot/triggerbot not working i since 15 days only esp works

I can say mine are working just fine using latest Hazedumper Offsets.
Your problem sure is somewhere else!



> dwLocalPlayer new value 0xD36B94

I just made new dumps for the latest update an created a pull-request. If you can't wait to get latest offsets, see my fork: https://github.com/s0t7x/hazedumper

**Comment by imbarismustafa** [comment]
@s0t7x Thanks! I am new to this and trying to learn at the same time. Looks like what I found matches with your offsets too with I am surprised. I posted this offset actually unsure of the value but was working on my end and is the one of the few I can find for now. Its literally my day one. Thanks for the link and will also look forward this to be updated soon.

**Comment by s0t7x** [comment]
@imbarismustafa you may be interested in this little snippet: [https://gist.github.com/s0t7x/e03ddf27c521fe3c4366c0a917ff784c](hazedumper-git-utilizer.cpp)

**Comment by keshav089** [comment]
@s0t7x  thanks i will check

**Pull request closed without merging**
