### PR TITLE
💡 "client_panorama.dll" -> "client.dll" due to unlogged csgo update (…

### PR DESCRIPTION
**Pull request by swoopae**
…6/4/20)

### CODE REVIEW

**Comment by swoopae** [comment]
did not dump new offsets since nothing important seems to have changed in the binary

**Comment by zoomzoom296** [comment]
Hi,

my offsets are not written by the program when updating hazedumper. What can I do?

**Comment by UpcomingWhale** [comment]
wait for the offsets to be updated or go find them yourself, cause they changed swoopae obviously didn't test

**Comment by f0xeri** [comment]
> Hi,
> 
> my offsets are not written by the program when updating hazedumper. What can I do?

change "client_panorama.dll" to "client.dll" in config.json

**Comment by zoomzoom296** [comment]
> 
> 
> > Hi,
> > my offsets are not written by the program when updating hazedumper. What can I do?
> 
> change "client_panorama.dll" to "client.dll" in config.json

There are several client_panorama.dll, should I change all of them?

**Comment by laurentksh** [comment]
> > > Hi,
> > > my offsets are not written by the program when updating hazedumper. What can I do?
> > 
> > 
> > change "client_panorama.dll" to "client.dll" in config.json
> 
> There are several client_panorama.dll, should I change all of them?

yes

**Comment by zoomzoom296** [comment]
"name": "dwForceJump",
      "extra": 0,
      "relative": true,
      "module": "client.dll",
      "offsets": 

is that correct?

**Comment by ReactiioN1337** [comment]
@swoopae they updated the binary ofc.

grafik

**Comment by frk1** [comment]
For future PR (no matter for which project) please limit the subject length to 50 chars; otherwise you get very ugly commits.

https://chris.beams.io/posts/git-commit/

**Pull request merged**
