### PR TITLE
Added python file for us python nerds

### PR DESCRIPTION
**Pull request by JacobC1921w**

### CODE REVIEW

**Comment by JacobC1921w** [comment]
> love u

Thanks man

**Comment by cr4ckker** [comment]
Holy cow! Tyvm <3

сб, 25 мар. 2023 г., 03:16 Jacob Collins ***@***.***>:

**Comment by ReactiioN1337** [comment]
I need to adjust the dumper, it's useless to submit the python file via PR.

**Comment by alsheikhaminulislam** [comment]
bro need new offset plzzzzz

**Comment by JacobC1921w** [comment]
> I need to adjust the dumper, it's useless to submit the python file via PR.

I've made a python script that just scrapes from the latest C# file, and converts it to python if you want that temporarily

**Pull request closed without merging**
