### PR TITLE
Update csgo.min.json 5/12/2022

### PR DESCRIPTION
**Pull request by pachara1337**

### CODE REVIEW

**Comment by 1256719039** [comment]
能不能看看啊

**Comment by pachara1337** [comment]
sorry I don't speak chinese

**Comment by 1256719039** [comment]
Can you tell me the offset

**Comment by 1256719039** [comment]
Do you have WeChat

**Comment by 1256719039** [comment]
Do you have csgo offsets?

**Comment by 1256719039** [comment]
Can friends in Bangkok make friends?

**Comment by pachara1337** [comment]
yes I do have csgo offsets

**Comment by pachara1337** [comment]
> Do you have csgo offsets?

you want .cs or .hpp

**Comment by 1256719039** [comment]
If we don't understand this, we won't use this

**Pull request closed without merging**
